### ISSUE TITLE
Error in rbind(deparse.level, ...) : 

### ISSUE THREAD

**Issue by OleksiyAnokhin** [shihikoo/pubmedTools#2]
Hi, how to resolve the error below? 

  > searchTerm = "query"
     > output <- RetriveMetaDataFromSearch(searchTerm)
     [1] "5525 publications found by the search."
     [1] "To retrieve publications:  1 - 500"
     [1] "Retrieved publications:  500"
     Error in rbind(deparse.level, ...) : 
     numbers of columns of arguments do not match

**Comment by shihikoo** [comment]
I tested the tool with your search term but got no error. All 5525 items were downloaded. Can you update your libraries and try it again?

**Comment by OleksiyAnokhin** [comment]
Perfect. Let me try tomorrow, I will update you! Thanks for a fast reply.

**Comment by OleksiyAnokhin** [comment]
Fixed. One more question. Can I add a column `secondary source` with Clinical trials niymber like `SI - ClinicalTrials.gov/NCT00000419`?

**Comment by shihikoo** [comment]
@OleksiyAnokhin Can you open another issue for the new question? I will close this issue now.
